name: Documentation Issue
description: Give us feedback on the documentation
title: "[docs]: "
labels: ["documentation"]
body:
  # information
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give us feedback!
  # feature description
  - type: textarea
    id: documentation-issue-description
    attributes:
      label: Description of the documentation issue
      description: |
        A clear and concise description of what the issue with documentation is.
        Please make proposals, how it could be done better.
      placeholder: Tell us what you want to see in the project!
    validations:
      required: true
  # additional context
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context about the feature here.
      placeholder: Anything that might help us understanding your documentation issue...
